package com.vieweat;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Entity // 1. Tells MySQL to make a table out of this
@Table(name = "user_profiles") // Renamed to avoid Supabase auth.users conflict
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // Unique ID (1, 2, 3...) auto-generated by MySQL

    @Column(name = "supabase_uid", unique = true)
    private String supabaseUid; // Link to Supabase Auth User ID

    @Column(unique = true, nullable = false)
    private String username;

    private String name;

    @Column(length = 1000)
    private String profilePicUrl;

    private String bio;

    @Column(length = 1000)
    private String tiktokUrl;
    @Column(length = 1000)
    private String instagramUrl;
    @Column(columnDefinition = "boolean default false")
private boolean isPublic;

    // --- THE RELATIONSHIP ---
    // One User has Many Reviews.
    // "mappedBy" tells MySQL to look at the 'user' field in the Review class to
    // find the link.
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL)
    private List<Review> reviews;
}
