--
-- PostgreSQL database dump
--

\restrict e1f4HRg7lx4Woe8HagTgdC9CrUuOEMYZbafsrgboTiSmFH6G2dfY3Su4qMhgC1f

-- Dumped from database version 14.20 (Homebrew)
-- Dumped by pg_dump version 14.20 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: food_items; Type: TABLE; Schema: public; Owner: simon
--

CREATE TABLE public.food_items (
    id bigint NOT NULL,
    description text,
    name character varying(255),
    rating double precision,
    review_id bigint NOT NULL
);


ALTER TABLE public.food_items OWNER TO simon;

--
-- Name: food_items_id_seq; Type: SEQUENCE; Schema: public; Owner: simon
--

ALTER TABLE public.food_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.food_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review; Type: TABLE; Schema: public; Owner: simon
--

CREATE TABLE public.review (
    id bigint NOT NULL,
    ambiance_score double precision,
    cuisine character varying(255),
    date character varying(255) NOT NULL,
    food_score double precision,
    instagram_url character varying(255),
    overall_desc text,
    overall_rating double precision NOT NULL,
    place_name character varying(255) NOT NULL,
    price_per_person real,
    service_score double precision,
    tiktok_url character varying(255),
    user_id bigint NOT NULL
);


ALTER TABLE public.review OWNER TO simon;

--
-- Name: review_id_seq; Type: SEQUENCE; Schema: public; Owner: simon
--

ALTER TABLE public.review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review_photos; Type: TABLE; Schema: public; Owner: simon
--

CREATE TABLE public.review_photos (
    id bigint NOT NULL,
    photo_url character varying(255) NOT NULL,
    review_id bigint NOT NULL,
    photo_order integer
);


ALTER TABLE public.review_photos OWNER TO simon;

--
-- Name: review_photos_id_seq; Type: SEQUENCE; Schema: public; Owner: simon
--

ALTER TABLE public.review_photos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_photos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: simon
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    bio character varying(255),
    email character varying(255) NOT NULL,
    instagram_url character varying(1000),
    name character varying(255),
    password character varying(255),
    profile_pic_url character varying(1000),
    tiktok_url character varying(1000),
    username character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO simon;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: simon
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: food_items; Type: TABLE DATA; Schema: public; Owner: simon
--

COPY public.food_items (id, description, name, rating, review_id) FROM stdin;
1	Wagyu Brisket, sauerkraught, swiss cheese, american mestard, pickles in rye bread	The Rueben	7.6	17
2	Roti was light and flaky and the peanut sauce was served warm. Only critique is the sauce didn’t have a strong enough peanut flavour for my liking.	Roti with Peanut Sauce	6.8	18
3	Found the chicken itself lacked flavour and was slightly dry. However, a generous serving of peanut sauce which is good	Chicken Satay Skewers with Peanut Sauce	6.8	18
4	Highlight of the show for me. A generous amount of sauce running through the noodles ensuring they are well flavoured with every single bite. The chicken and tofu within the noodles also benefitted from the sauce providing a flavour bomb in your mouth.	Chicken Phad Thai	8.4	18
5	The beef within the curry was phenomenal. Melt in your mouth stuff. The curry itself was ok, a flavour bomb like every curry should be. Served with fragrant jasmine rice it was a fabulous duo.	Beef Massaman Curry	7.4	18
\.


--
-- Data for Name: review; Type: TABLE DATA; Schema: public; Owner: simon
--

COPY public.review (id, ambiance_score, cuisine, date, food_score, instagram_url, overall_desc, overall_rating, place_name, price_per_person, service_score, tiktok_url, user_id) FROM stdin;
1	7.2	Japanese	2025-12-05	7.8		This week we have a small Japanese cafè on Toorak road in Camberwell, recommended by the signora jagamina. I have never been to a japanese cafè and after this experience I want to go to more. I love the vibe, the menu, the drinks list it's so cool. \n\nThey had all these specialty coffee brews and tea options. Plus, the food choices were very very good. Now, the sushi bowl was light, fresh, super tasty and filled me up to an extent. The salmon sashimi was fresh, as with all the ingredients in the bowl as well. \n\nJas had the chicken katsu curry which I must admit the chicken katsu was some of the best if not the best I have ever had. The curry itself was nice, but nothing the blew me out of my chair. \n\nIn all honestly, the value, service and vibes of the place were great. You can't really go wrong and it is a very solid visit, and a good spot to impress a date or take a mate for lunch. Also to note they do dinner as well but unsure of what the menu looks like for that.	7.6	Haiku	25.5	7		1
3	\N	Mexican	2025-12-07	\N		Had a little date with Pietro this week to Sam's Cantina on chapel street. An aethestic mexican casual cantina. \n\nPietro and I don't muck around with food and we start with the Birria amd crispy fish tacos and a side of nachos. Nachos were standard, birria tacos had good strong spice flavour and not too oily. The meat was a bit tough imo for a slow roasted pulled beef. The crispy fish tacos surprised me and were probably my favourite of the day, the crumb was crunchy, and the spicey aoili with pickled onion were a great pairing. \n\nWe were naturally still hungry so we ordered some pulled pork, birria loaded chips and some chicken tenders. The pulled pork tacos, although decent flavour, were way too oily for me. I like juicy meat but this was too much, it was just way too fatty/oily. However, the grilled cheese, guac and pickled onions saved the taco I must admit. The birria loaded fries were okay, the birria beef was again a bit tough but the combo was alright. The tenders were a bit of a let down relative to other tenders I've had. Chicken on the inside was fine (not dry not juicy) and the crumb on the outside was too crunchy. It just didn't work for me. \n\nPlace was a bit pricey overall but we were on Chapel street so that is expected. I wouldn't personally recommend as there is better mexican around in my opinion such as Cartel Del Taco which is about 5mins from this place (shoutout @katsgotswag)	6.4	Sam's Cantina	65	\N		1
6	8.8	Chinese	2025-08-29	9		Tucked away just off Little Burke in China, this resturant has been here since 1975. Aged like fine wine, the waiters and staff (many who have been there for over 40 years) are absolute professionals with eyes like Eagles, attending to every minor detail delicately and swiftly. Only adding to the experience itself. \n\nThe food, although not abundant in size, was touched by THE maneki-neko (lucky chinese golden cat) and was absolutely superb. There was not a single dish that I could completely fault. They were all super high quality and carrying a well-balanced authentic Cantonese flavour.  \n\nBefore going to the resturant, I will admit I was a bit hesitatant given the price vs portion size vs my appetite, but, I persisted (I wasn't paying 😏). Needless to say post-feed I would with certainty go again and would pay with pleasure. Although I have only been once, I feel although with 50 years of experience this institution is a place you can be guaranteed to have amazing food and service.	9	Flower Drum	\N	9.2		1
7	\N		2025-08-30	\N		I think im going to structure these in depth ones depending on how fancy or casual the place is. So, the more fancy the more serious the less fancy less serious. \n\nSo, this place is near the corner of Burke Rd and Mont Albert Rd in an old Garage place. They've done it up to be all hip and cool, like that typical trendy diner/sandwich places popping up everywhere these days. Look, I walked in and I asked the person serving me "what do you do best?". Now, they went and basically said the whole menu 🥴. Yep 👍. Soooooo anyway I went with the Calzone cause it was the first one they said and it looked good to me. \n\nToo be totally fair ive given this place a 6.8/10 but the calzone's taste was incredibly solid. I mean the chilli-jam really made it, that hint of sweetness with the straciatella and the fresh warm dough was great. But really, I got 3 slices of Mortadella, two spoons of straciatella, a smither of pesto spread and only half of the calzone had enough Chilli jam to ACTUALLY taste it. Paying $20 for a sandwich is already steep in the trendy sandwich world, but mortadella is not expensive so give me a couple more slices man.	6.8	Barry's Garage	\N	\N		1
8	\N		2025-09-09	\N		Been all over my socials, big fat loaded rolls stacked with ham, prosciutto, salami, provolone, peppers, olives, pesto... Rocco's Deli. Nothing too fancy from the outside just looks like a old milk bar re-purposed to serve rolls. \n\nI was accompanied by trusty kiko who was whining in the car that he wanted more protein and he hates wasting hunger on bad food. I go kiko man just load the thing. Kiko gets up to the counter and goes "do you guys have Jamon?". I'm thinking, is this guy an idiot its an Italian deli, just get prosciutto. Anyway, the server says yes, kiko looks at me and smirks and proceeds to go without taking a breath and pausing "can i get a rocco roll with double Jamon, double Prosciutto, double Provalone, and no eggplants". Anyway, you'd expect this to be a good $50 for two rolls considering the extras and modifications we were making. Came out to $38. Bargain!\n\nThen, the rolls come out, I kid you not kikos is at least 1kg in weight with half of it being meat. Mine was maybe 1/2 of that. Anyway, the Jamon, was not Spanish Jamon and was ham. Serves him right. \n\nTo the review... fresh bread, high quality meats with generous servings, amazing pesto base, and adequate deli peppers, olives and eggplants to provide needed moisture and vinegar to the roll. From a quality standpoint fantastic. Price standpoint, unreal value. X factor standpoint? That's where I think it lacks. But what did I expect? If you want a good basic roll at a reasonable cost look no further. It's a solid feed and if I lived around the area I'd certainly frequent the place. However, being in Yarraville I don't see myself returning as it is nothing unique or worth the 45min hike unless I'm in the area.	7.2	Rocco's Deli	16.5	\N		1
9	\N		2025-09-12	\N		Been on my radar for wayyyyyy to long. But, this visit was prompted by a viewer of the segment. Can't say I'm too experienced in the hot/fried chicken relm, however, I know what good food tastes like. \n\nStraight off the bat, hit up the one in the CBD (they have another in Fitzroy) with none other then my boyfriend kiko for a cute little date. We ordered the $68 combo with two burgers, 4 tenders, basket of chips, slaw and 3 different sauces. The inside was American diner themed and was packed to the brim (which is always a good sign).\n\nThe Nashville burger was easily the highlight of the meal, chicken thigh was super Crispy on the outside and juicy on the inside, bun was immaculate, and their good good sauce was, well, good. Chips were elite, being crinkle crinkle crinkle crinkle cut with some nice paprika type seasoning. Tenders were good, nothing crazy but still solid, not as Crispy or juicy as the Nashville chicken fillet. \n\nValue wise it's pretty good at $34pp for high quality protein that kept me quite full for the next 5 hours. (We could barely finish all the food, and left some of the salad)\n	8.3	Belle's Hot Chicken	34	\N		1
10	\N		2025-09-13	\N		Third time indulging in the Leon's Smash Burgers, but first time for Leon and Coop. I promised these boys a good feed... Did they enjoy it as much as I did? I'm not quite sure. Did they smash the burger down their gob? They sure did. \n\n I must say Leon does his Burgers almost exactly how I like them. Flat like a pancake, soft Martin's bun, creamy melted American cheddar cheese, special sauce, diced onions, and crinkle cut pickles. For me, the absolute perfect combination, a higher-class Maccas cheeseburger if you insist. \n\nPreviously I have rated these at a 9.8/10 in my extensive food rating archives. However, on this occasion young and passionate Leon has ever so slightly let me down. Now, I have to give him credit, every pop-up is a new kitchen set-up and he must get used to it. However, we are ruthless out here. The beef burger patties were a bit dry this time. Which is a HUGE determinant in a good burger. So, unfortunately for Leon I have to reduce what was an incredible rating to a 8.9/10. With a lack of fries or any sides for that matter, my new burger rating metric system ceases Leon to go above a 9.0/10 unfortunately (there is science behind my ratings).	8.9	Leon's Smash Burgers	16	\N		1
11	\N	Greek	2025-09-18	\N		Quick and easy one this week. Hellenic depot. If you ask me for my go to casual Greek in Melbourne it's this place. I think I've been here 5 or 6 times in the past year and it never fails to dissapoint me. \n\nOne Platter is enough to get me full. If you know me I eat a lot, so that's impressive. The meat is done on the charcoal and is very well seasoned. The chips are immaculate and this time round the best I've had there. The salad was just ok, but the Pita and Tzatziki were amazing. \n\nThe place was fully packed at 6:15 on a Thursday night as it always is, and I think it still flys under the radar a bit given the popularity of the Oakleigh hub not too far from it.	8.2	Hellenic Depot	36	\N		1
12	\N	Italian	2025-09-20	\N		This meal right here is quite honestly one of if not the best sandwhich I've had in Melbourne to date. For $15 you're getting a loaded roll with a thick schnitzel, juicy iceberg lettuce, and a generous serving of parmasen cheese. \n\nThis one was a solo mission, sat at the bar by myself, chatted to the the Italiano behind the bar and ate my roll in peace. The place was very busy with people sitting and having lunch (it's a proper resturant) but only me having the lunch special from what I could see. Given it's not even a deli/sandwhich place they sure know what they are doing. Will be returning here if I'm in the area.	8.6	Marameo	15	\N		1
13	8.3	Japanese	2025-10-01	8.6		So, Tokyo Tina in Parahn on Chapel Street is a modern Japanese restaurant that offers diners an extensive menu. The resturant itself is nothing too eye-catching from the front, however, inside it is nice and moody, perfect for a date night. Blessed to have the beautiful Jas join me for our late anniversary dinner. \n\nWe asked the waiter what they recommend, and to our credit what they recommended is what we were thinking…\n\nWe started off with some fresh dishes which included the spicy salmon tatare served with some seaweed puffed crisps. Jas loved this dish and so did I, too be fair. It was light and fresh, dressed with a nice soy vinaigrette and tossed with some Yuzu and spring onions. In conjunction with this we had the open spicy tuna rolls… this was unreal. The tuna was fresh, rice was warm, and the seaweed you DIY wrap it in actually tasted like seaweed, which I quite enjoyed.\n\nThen came out the DIY pork bao buns. Look, all the ingredients were good and tasted nice with the sauces they provided. However, I don’t think I liked the idea of constructing this by myself. I feel like I would have been happier if they sliced it themselves and then served it to build as when I cut it (with the somewhat dull knife) the pieces were too thick and it just ruined it a bit in my opinion. However, we are just being critical here and it was still a decent bao bun.\n\nFollowing this dish, the fried pork gyozas and chicken karage came out. Let me just say that chicken karage was gooooooood. It had a side of Kewpie and lemon, which was the perfect touch to the dish. The pork gyozas were okay, filling was nice, however, I felt they were a bit too greasey/oily. \n\nNow, for the last main dish we got the miso butter stripoloin which was absolutely unreal. That miso butter with the hibachi grilled steak was a great combination of flavours. I think we need more miso butter steaks going around because that was a flavour combination I want to have again. For me, easily the dish of the night.\n\nLastly, for dessert, we got the chocolate caramel fondant. They are not easy to do well, but when they are done well, a fondant/soufflé gotta be top 5 desserts for me. This one was indeed done well, not the best I’ve ever had, but satisfactory to finish off a good meal.\n\nOverall a very solid meal which I thoroughly enjoyed with good service.  I would recommend this to a friend and would definitely return.	8.3	Tokyo Tina	100	8		1
14	\N	American	2025-10-03	\N		Was craving for a while to head down to Ivanhoe and try out the Cootsey box. Thankfully, this month it is on the specials list. I was joined by Pietro, and lucky I was. The feed was massive and beautiful. \n\nThe cootsey box comes with a double smash burger, two tenders, loaded fries (which have another smash patty on them), and a big container of their special sauce for $36. In my opinion phenomenal value. The box on its own got me satiated, which isn't exactly an easy feat. I've been here about 4 times over the past 2 years and I have to admit the food was the best it has ever been. The tenders were juicy, burger patties were thin and crispy, and the chips were perfect. \n\nAdditionally, Pietro and I got some hot honey bonless thighs from glory fryed as a little side. These were above average, definintely juicy and crispy but the flavour itself was a bit lackluster in my opinion.	9	College Dropout X Glory Fryed	42	\N		1
15	\N	Greek	2025-10-11	\N		Two weeks in a row joined by Pietro. This week led by him he took me to Pita Wrap It in Oakleigh. Typical greek resturant with lots of meat and some sides. The place does all the meat over the charcoal which is always a winner. \n\nWe got a fried feta with honey which was okay, I think I was a bit spoiled in Greece and my expectations are quite high. We also then got a dip platter which the dips were really good and definitely made in house due to their fluffy texture (tarama, tzaziki, melitzanosalata, tyrokafteri)\n \nFor main we got the big mix grill meat platter. It came with one big chicken skewer, one big lamb skewer, 2 sousages, 4 pork chops, 2 lamb fillet things, a genrrous amount of mixed gyro meat, a bowl of chips, 2 pita wraps, a mixed greek salad. Let me just say value for money here is insane this could be easily shared between 3 people and would come out to roughly $20ish pp. The meat was good definitely above average. Way too salty (and I love salt). Flavour was decent but not strong enough flavours for me. The chips were quite good and the pita was standard. \n\nIf it were me I'd drive 3mins down the road and go to Hellenic Depot in Hughsdale. Overall better food, vibe, and is always packed (with good reason).	6.8	Pita Wrap It	52.5	\N		1
16	\N		2025-10-14	\N		Popped into It's Bagels in the cbd with the sister. Haven't had a loaded bagel ever so expectations were non-existent. Starting off with the Loxury bagel with the black pepper cheese bagel. It had smoked salmon, cream cheese, tomato, onion, pickle and cos lettuce. Probably the better bagel of the two, salmon wasn't too smokey, tomato was fresh, pickle had a bit of bite, and the bagel itself was different. \n\nNext was the crispy chicken in a poppy seed bun, with crispy chicken, onion, tomato, iceberg lettuce, cheese, and mayo. The chicken was juicy but crispy on the outside, however, my issue with this one is the slab of onion was the same thickness as the chicken. Cannot be having that, kind of ruined the bagel (I took it out anyway) not my cup of tea. \n\nAnother issue I had with this place generally was it was really hard to eat the bagels. They were packed with stuff, which is good! But the bagels themselves were too small for the amount that was in them, making it hard to eat with things falling out easily. 	6.3	It's Bagel	17	\N		1
17	\N		2025-10-24	\N		Tried out the Ruben from Vic's meats in the market pavillion at chaddy a couple weeks ago. It is their take on the famous Katz deli from New York. \n\nI must say I was sceptical on the combination in the sandwhich itself and how it all works. But, the mixture of vinegar (from the pickles and sauerkraught) plus the mustard and brisket works super well. The sandwhich itself was super loaded and the meat was butter soft. Apart from the lethal amount of fat juices oozing out of the meat (which takes some points off) there isn't much to complain about taste wise. Price is definietly steep at $24 but I guess the ingredients are expensive (especially the meat) and it was well loaded in their defense. \n\nI have no idea what the Katz deli sandwhich tastes like but if you've got an inkling to have a taste of something similar I'd grab one of these next time you are at chaddy.	7.6	Vic' Meat	24	\N		1
18	7	Thai	2025-11-14	7		Overall, the serving sizes were very generous, especially at the price point. Fat Boy has been solid for many years and I continue to come back both dine in and takeaway. Their Thai is generally more sweeter flavours than the spice meaning it probably isn’t super authentic stuff. But, I love it and it has been my go-to takeaway spot for Thai for about 7 years. Very casual spot, reasonabley priced food with generous servings and good flavours.	7	Fat Boy	36	7		1
19	\N	Korean	2025-11-15	\N		This is absolutely phenomenal chicken. Ladies and gentlemen this is easily the easily the best fried chicken I have had in Melbourne. It is a little hike to west melbourne not too far from Marvel stadium. But seriously I would happily travel back here without second thought. \n\nThe outside of the chicken was light and crispy but the inside was juiceyyyyyyyyyy. Also, they do not skip out on the flavouring. These are absolute flavour bombs and there were zero misses. Best flavour was the lemon pepper which was just divine. Second was the honey soy garlic. Then the sweet n spicey and original were tied third. \n\nCheese dusted waffle fries were also elite. Nothing like anything I've had before, and I really rate that\n\nDidn't give it higher purely because I just feel there COULD be something better in the Fried Chicken realm. But there isn't for the time being in my opinion.	9.2	Bandak	25.5	\N		1
20	\N		2025-11-21	\N		Not much to say but seriously dissapointed. I have seen Hugo's deli on my socials for a while now and thought it surely had to be good. \n\nI ordered a cripsy chicken sandwhich and added cheese for $1. The food came out and the cheese was a slice of chedder (questionable charging $1 for it), the bread was too thick imo, the sandwhich was probably 12x12cm in size, the chicken inside the crumbing was maybe 0.5cm thick and the crumbing was tasteless. \n\nAfter the first bite I was already telling kiko how it was no good in my opinion. For some positives their pickle mayo spread was nice, the bread was very soft and fresh, and the chicken was cooked well.  However it was ultimately a dissapointment for me.	5.6	Hugo's Deli	18	\N		1
\.


--
-- Data for Name: review_photos; Type: TABLE DATA; Schema: public; Owner: simon
--

COPY public.review_photos (id, photo_url, review_id, photo_order) FROM stdin;
1	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448283/pb6upbn971wyp9gqgm2r.jpg	1	2
2	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448274/gpzgx7gmh4aevg3dgqxb.jpg	1	1
3	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448293/utnhoqusoa6t35gzc5gu.jpg	1	3
4	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448265/srjkridx916i0bbjlafd.jpg	1	0
7	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448305/lh3peret1mtskr6llrbw.jpg	3	0
8	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448318/q3vjtmmesyxbtl6owovp.jpg	3	1
9	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448329/dwnjsmpzclqnkbngod9e.jpg	3	2
10	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448335/bfe6xtnjkww4cskmn7vz.jpg	3	3
11	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448345/wx9atmqbewao46h1mogh.jpg	3	4
12	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448362/kfu5kxlh9i5bfzb35fhz.jpg	3	5
13	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448371/babyy3lng9nizevmemi8.jpg	3	6
20	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448375/a3zvntutl1ehlwatp7zz.jpg	6	0
21	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448381/xkjgdvhw5iwh28f186j8.jpg	6	1
22	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448387/gsspp0g3kpkdayybhi5f.jpg	6	2
23	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448395/onyxxexjx6idbsg42bag.jpg	6	3
24	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448406/e0qtijcmvxefmmikbknb.jpg	6	4
25	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448416/lc7uwuregltnwbc1ijjt.jpg	6	5
26	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448422/ajhgun48oa8q9zy1bt6r.jpg	6	6
27	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448434/vsdrci54evsvv4ksqpp8.jpg	7	0
28	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448437/ra9nwfgfj0si9hyesraz.jpg	7	1
29	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448444/l9hss0m3gn4qdyfiblct.jpg	7	2
30	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448449/r6orzz8pf32pxoru8l6o.jpg	7	3
31	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448455/coqgqazxmwwy0hmqopsn.jpg	8	0
32	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448464/diihrle5ougikdqu4lrr.jpg	8	1
33	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448472/v9lbcehwo1c3snsnwhe5.jpg	8	2
34	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448476/refpilay91wd5j2mka6k.jpg	8	3
35	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448482/wclxrfxovrbrp5aff0ay.jpg	9	0
36	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448491/vx7btjxvl56qazg9mjp7.jpg	9	1
37	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448497/atrqypg1vrbs0w6lnzbm.jpg	9	2
38	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448501/bpkj3rswdg8br0e5en67.jpg	9	3
39	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448510/ylhj4pnjo5qvxamr2d85.jpg	9	4
40	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448520/eddylzyooe0lct84au8l.jpg	10	0
41	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448524/tlsvgthaibvgihpvd8ad.jpg	10	1
42	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448530/j0dz9ntxbcxnsw8r3rub.jpg	11	0
43	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448543/fhqfcaeu7pp6gxqwbfrg.jpg	11	1
44	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448550/ww0jhhktyh0xqbv7wn1m.jpg	12	0
45	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448556/woqexrtokxlqx4c6qexe.jpg	12	1
46	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448566/yqy2iqdzjjbafwxcvj3e.jpg	12	2
47	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448571/enfusahxppygtgwpyaom.jpg	13	0
48	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448580/btkubpqrls8ollut97om.jpg	13	1
49	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448601/b2io4ahvz55dhnmkeen5.jpg	13	2
50	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448606/ovlp3btxjeuows2cxjnn.jpg	13	3
51	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448611/xx1x7iotwtzsblsozbnc.jpg	13	4
52	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448620/qc8lazw2yi0eesfgfivg.jpg	13	5
53	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448623/knxooi96kusexcaespgd.jpg	13	6
54	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448635/e6t4azvx1w1kp0k1yfae.jpg	13	7
55	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448644/vnsvirb6lcw28eiyz8oj.jpg	13	8
56	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448654/l8bvlydlilxafmj7isnn.jpg	14	0
57	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448665/svio5ksfzpkx8ivmrt35.jpg	14	1
58	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448672/wifi35b3lmplf6svmxit.jpg	14	2
59	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448679/oqtnp4nekczzmoei1ztb.jpg	14	3
60	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448683/rd2aqpuuxjqjukdb3osb.jpg	14	4
61	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448693/t8mvcn34xequvccqvfj1.jpg	15	0
62	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448704/vcrlrdkmivtyc83hqd1a.jpg	15	1
63	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448715/oykmxwog4xzpxpr9tyfj.jpg	15	2
64	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448728/p8sswv58ckvzbidddsya.jpg	15	3
65	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448735/pkxhdzoout597guahgro.jpg	16	0
66	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448742/z8pvv8rniupulo8pkcpc.jpg	16	1
67	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448753/lpswmhxm6pfbnfha5amw.jpg	16	2
68	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448759/pereb8vqy3d5t3oslupv.jpg	16	3
69	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448766/aqnzqqb3xqs8vccouhzy.jpg	17	0
70	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448776/qkh4gjgtsmcghaaks8in.jpg	17	1
71	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448781/i2ezabbxkp8irilojyjc.jpg	17	2
72	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448786/lwkbibkraoesgxcoeijc.jpg	18	0
73	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448798/tzhle3z4aifhd125wljv.jpg	18	1
74	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448809/vm5jq24yir63zj1husya.jpg	18	2
75	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448819/vk6b3hils6qnfor4scuj.jpg	18	3
76	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448825/ubdc0ahnfs0hugqeu2th.jpg	18	4
77	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448837/fi1eslfqntuhzernzw8j.jpg	18	5
78	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448848/htficopqkxpjndorgdbp.jpg	19	0
79	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448854/erocqbxgfzehvfrjwvip.jpg	19	1
80	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448859/s7g9jo7vu2jpdslyrmio.jpg	19	2
81	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448868/yboorzc1jzgzcqchxde4.jpg	19	3
82	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448877/zb4q1w5fxfgu1xg3z1kl.jpg	19	4
83	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448883/x4qstgz4tyjkzdzdohqs.jpg	19	5
84	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448894/wmdsl4unhfmprerfvqq5.jpg	19	6
85	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448901/dfg7h5l2ruvmglpdeqbo.jpg	20	0
86	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448906/x5eyanakrtzuf89p2atl.jpg	20	1
87	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448912/rrrbbs0kvtm6puwfubvp.jpg	20	2
88	https://res.cloudinary.com/dylqflxeg/image/upload/v1766448918/narsejudzajmarwzfvj4.jpg	20	3
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: simon
--

COPY public.users (id, bio, email, instagram_url, name, password, profile_pic_url, tiktok_url, username) FROM stdin;
1	Lets Eat...	simon@vieweat.com	https://www.instagram.com/simon.katsiamakis/	Simon Katsiamakis	{noop}Iyafgfar!	https://res.cloudinary.com/dylqflxeg/image/upload/v1766450768/ttuiyvbbre02rvreeuuo.jpg	https://www.tiktok.com/@simon_katsiamakis?is_from_webapp=1&sender_device=pc	skatsi07
\.


--
-- Name: food_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: simon
--

SELECT pg_catalog.setval('public.food_items_id_seq', 5, true);


--
-- Name: review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: simon
--

SELECT pg_catalog.setval('public.review_id_seq', 21, true);


--
-- Name: review_photos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: simon
--

SELECT pg_catalog.setval('public.review_photos_id_seq', 91, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: simon
--

SELECT pg_catalog.setval('public.users_id_seq', 1, true);


--
-- Name: food_items food_items_pkey; Type: CONSTRAINT; Schema: public; Owner: simon
--

ALTER TABLE ONLY public.food_items
    ADD CONSTRAINT food_items_pkey PRIMARY KEY (id);


--
-- Name: review_photos review_photos_pkey; Type: CONSTRAINT; Schema: public; Owner: simon
--

ALTER TABLE ONLY public.review_photos
    ADD CONSTRAINT review_photos_pkey PRIMARY KEY (id);


--
-- Name: review review_pkey; Type: CONSTRAINT; Schema: public; Owner: simon
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: simon
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: simon
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: simon
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: review fk6cpw2nlklblpvc7hyt7ko6v3e; Type: FK CONSTRAINT; Schema: public; Owner: simon
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fk6cpw2nlklblpvc7hyt7ko6v3e FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: review_photos fk6qulnqispsas4dhsguanjit77; Type: FK CONSTRAINT; Schema: public; Owner: simon
--

ALTER TABLE ONLY public.review_photos
    ADD CONSTRAINT fk6qulnqispsas4dhsguanjit77 FOREIGN KEY (review_id) REFERENCES public.review(id);


--
-- Name: food_items fkgm3ddn2dflecjargh3olweri; Type: FK CONSTRAINT; Schema: public; Owner: simon
--

ALTER TABLE ONLY public.food_items
    ADD CONSTRAINT fkgm3ddn2dflecjargh3olweri FOREIGN KEY (review_id) REFERENCES public.review(id);


--
-- PostgreSQL database dump complete
--

\unrestrict e1f4HRg7lx4Woe8HagTgdC9CrUuOEMYZbafsrgboTiSmFH6G2dfY3Su4qMhgC1f

