spring.application.name=vieweat

# 1. Database Connection Setup (Supabase Production)
spring.datasource.url=jdbc:postgresql://db.voqprdlmfgdldefqvjzs.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# 2. Hibernate Settings (The Magic)
# "update" means: If I change my Java class, automatically update the MySQL table to match.
spring.jpa.hibernate.ddl-auto=update

# Optional: Show the SQL in the console so you can see what's happening
spring.jpa.show-sql=true

# --- FILE UPLOAD LIMITS ---
server.tomcat.max-part-count=200
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
server.tomcat.max-http-form-post-size=100MB

# 3. Supabase Configuration
supabase.url=${SUPABASE_URL}
supabase.anon-key=${SUPABASE_ANON_KEY}
supabase.jwt-secret=${SUPABASE_JWT_SECRET}
