package com.vieweat;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Entity // 1. Tells MySQL to make a table out of this
@Table(name = "users") // 2. Name the table "users"
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // Unique ID (1, 2, 3...) auto-generated by MySQL

    @Column(unique = true, nullable = false)
    private String username;

    @Column(unique = true, nullable = false)
    private String email;

    private String name;

    private String password;
    
    @Column(length = 1000)
    private String profilePicUrl;
    
    private String bio;

    @Column(length = 1000)
    private String tiktokUrl;
    @Column(length = 1000)
    private String instagramUrl;

    // --- THE RELATIONSHIP ---
    // One User has Many Reviews. 
    // "mappedBy" tells MySQL to look at the 'user' field in the Review class to find the link.
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL)
    private List<Review> reviews;
}
